services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongo_dab
    user: "0:0"
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db

  fastapi:
    build: .
    container_name: microservice_fastapii
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongo:27018

volumes:
  mongo_data:


